sectionPagesMenu = "main"

baseURL = 'https://astridmalter.com/'
languageCode = 'en-us'
title = 'Astrid Malter'

hideColorSchemeToggle = true
theme = 'hugo-theme-ava'

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 10
[[menu.main]]
  name = 'About'
  url = '/about'
  weight = 20
[[menu.main]]
  name = 'Contact'
  url = '/contact'
  weight = 30